import { getDb } from "./db.js";

const db = await getDb();

await db.execute(`DROP TABLE IF EXISTS \`permissions\`;`);
await db.execute(`DROP TABLE IF EXISTS \`organizations_users\`;`);
await db.execute(`DROP TABLE IF EXISTS \`organizations\`;`);
await db.execute(`DROP TABLE IF EXISTS \`users\``);
await db.execute(`
CREATE TABLE \`users\` (
  \`id\` int unsigned NOT NULL AUTO_INCREMENT,
  \`phone_number\` varchar(255) DEFAULT NULL,
  \`email\` varchar(255) DEFAULT NULL,
  \`first_name\` varchar(255) NOT NULL,
  \`last_name\` varchar(255) NOT NULL,
  \`img\` varchar(255) DEFAULT NULL,
  \`password\` varchar(128) DEFAULT NULL,
  \`salt\` varchar(64) DEFAULT NULL,
  \`activated_at\` datetime(3) DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  \`deleted_at\` datetime(3) DEFAULT NULL,
  \`last_visited_at\` datetime(3) DEFAULT NULL,
  \`creator_id\` int unsigned DEFAULT NULL,
  \`creation_method\` enum('SELF','IMPORT','WEB_DIRECT','NATIVE_DIRECT','INVITE_LINK','SAML') DEFAULT NULL,
  \`onboarding_method_id\` int unsigned DEFAULT NULL,
  \`onboarding_completed\` tinyint(1) NOT NULL DEFAULT '0',
  \`exclude_from_analytics\` tinyint(1) NOT NULL DEFAULT '0',
  \`last_invite_sent_at\` datetime(3) DEFAULT NULL,
  \`auth_type\` enum('NORMAL','SAML') DEFAULT 'NORMAL',
  \`sign_up_method_id\` int unsigned DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`users_email_unique\` (\`email\`),
  UNIQUE KEY \`users_phone_number_unique\` (\`phone_number\`),
  KEY \`users_creator_id_foreign\` (\`creator_id\`),
  CONSTRAINT \`users_creator_id_foreign\` FOREIGN KEY (\`creator_id\`) REFERENCES \`users\` (\`id\`) ON DELETE SET NULL
);
`);
await db.execute(`CREATE TABLE \`organizations\` (
  \`id\` int unsigned NOT NULL AUTO_INCREMENT,
  \`name\` varchar(255) NOT NULL,
  \`industry_type_id\` int unsigned DEFAULT NULL,
  \`img\` varchar(255) DEFAULT NULL,
  \`creator_id\` int unsigned DEFAULT NULL,
  \`updater_id\` int unsigned DEFAULT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  \`deleted_at\` datetime(3) DEFAULT NULL,
  \`default_location_id\` int unsigned DEFAULT NULL,
  \`exclude_from_analytics\` tinyint(1) NOT NULL DEFAULT '0',
  \`trial_end_date\` datetime(3) DEFAULT NULL,
  \`creation_platform\` varchar(255) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`organizations_creator_id_foreign\` (\`creator_id\`),
  KEY \`organizations_updater_id_foreign\` (\`updater_id\`),
  CONSTRAINT \`organizations_creator_id_foreign\` FOREIGN KEY (\`creator_id\`) REFERENCES \`users\` (\`id\`) ON DELETE SET NULL,
  CONSTRAINT \`organizations_updater_id_foreign\` FOREIGN KEY (\`updater_id\`) REFERENCES \`users\` (\`id\`)
);
`);
await db.execute(`CREATE TABLE \`organizations_users\` (
  \`id\` int unsigned NOT NULL AUTO_INCREMENT,
  \`organization_id\` int unsigned NOT NULL,
  \`user_id\` int unsigned NOT NULL,
  \`role\` enum('ADMIN','MEMBER','REQUESTER','SERVICE_ACCOUNT') NOT NULL,
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  \`activated_at\` datetime(3) DEFAULT NULL,
  \`last_visited_at\` datetime(3) DEFAULT NULL,
  \`inviter_id\` int unsigned DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`organizations_users_organization_id_user_id_unique\` (\`organization_id\`,\`user_id\`),
  KEY \`organizations_users_user_id_foreign\` (\`user_id\`),
  KEY \`organizations_users_inviter_id_foreign\` (\`inviter_id\`),
  CONSTRAINT \`organizations_users_inviter_id_foreign\` FOREIGN KEY (\`inviter_id\`) REFERENCES \`users\` (\`id\`),
  CONSTRAINT \`organizations_users_organization_id_foreign\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`organizations_users_user_id_foreign\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
);
`);
await db.execute(`CREATE TABLE \`permissions\` (
  \`id\` int unsigned NOT NULL AUTO_INCREMENT,
  \`organization_id\` int unsigned NOT NULL,
  \`priority\` int NOT NULL,
  \`presets\` bigint unsigned NOT NULL DEFAULT '0',
  \`created_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  \`updated_at\` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  \`user_id\` int unsigned DEFAULT NULL,
  \`team_id\` int unsigned DEFAULT NULL,
  \`role\` enum('ADMIN','MEMBER','REQUESTER') DEFAULT NULL,
  \`work_order_view_all\` tinyint(1) DEFAULT NULL,
  \`work_order_view_extended\` tinyint(1) DEFAULT NULL,
  \`work_order_create\` tinyint(1) DEFAULT NULL,
  \`work_order_edit\` tinyint(1) DEFAULT NULL,
  \`work_order_procedure_edit\` tinyint(1) DEFAULT NULL,
  \`work_order_archive\` tinyint(1) DEFAULT NULL,
  \`work_order_cancel\` tinyint(1) DEFAULT NULL,
  \`work_order_action_alias\` tinyint(1) DEFAULT NULL,
  \`work_order_action_status\` tinyint(1) DEFAULT NULL,
  \`work_order_action_reopen\` tinyint(1) DEFAULT NULL,
  \`work_order_action_procedure\` tinyint(1) DEFAULT NULL,
  \`work_order_action_parts\` tinyint(1) DEFAULT NULL,
  \`work_order_select_requester\` tinyint(1) DEFAULT NULL,
  \`work_order_comment_read\` tinyint(1) DEFAULT NULL,
  \`work_order_comment_write\` tinyint(1) DEFAULT NULL,
  \`work_request_approve\` tinyint(1) DEFAULT NULL,
  \`work_request_create\` tinyint(1) DEFAULT NULL,
  \`work_request_archive\` tinyint(1) DEFAULT NULL,
  \`work_request_view\` tinyint(1) DEFAULT NULL,
  \`work_request_portal_view\` tinyint(1) DEFAULT NULL,
  \`work_request_portal_create\` tinyint(1) DEFAULT NULL,
  \`work_request_portal_edit\` tinyint(1) DEFAULT NULL,
  \`work_request_portal_archive\` tinyint(1) DEFAULT NULL,
  \`webhook_archive\` tinyint(1) DEFAULT NULL,
  \`webhook_create\` tinyint(1) DEFAULT NULL,
  \`webhook_view\` tinyint(1) DEFAULT NULL,
  \`rest_api_token_archive\` tinyint(1) DEFAULT NULL,
  \`rest_api_token_create\` tinyint(1) DEFAULT NULL,
  \`rest_api_token_view\` tinyint(1) DEFAULT NULL,
  \`team_create\` tinyint(1) DEFAULT NULL,
  \`team_list\` tinyint(1) DEFAULT NULL,
  \`team_edit\` tinyint(1) DEFAULT NULL,
  \`team_archive\` tinyint(1) DEFAULT NULL,
  \`reporting_view\` tinyint(1) DEFAULT NULL,
  \`export_data\` tinyint(1) DEFAULT NULL,
  \`location_create\` tinyint(1) DEFAULT NULL,
  \`location_edit\` tinyint(1) DEFAULT NULL,
  \`location_archive\` tinyint(1) DEFAULT NULL,
  \`asset_create\` tinyint(1) DEFAULT NULL,
  \`asset_type_edit\` tinyint(1) DEFAULT NULL,
  \`asset_edit\` tinyint(1) DEFAULT NULL,
  \`asset_custom_status_archive\` tinyint(1) DEFAULT NULL,
  \`asset_custom_status_create\` tinyint(1) DEFAULT NULL,
  \`asset_custom_status_edit\` tinyint(1) DEFAULT NULL,
  \`asset_status_archive\` tinyint(1) DEFAULT NULL,
  \`asset_status_create\` tinyint(1) DEFAULT NULL,
  \`asset_status_edit\` tinyint(1) DEFAULT NULL,
  \`asset_archive\` tinyint(1) DEFAULT NULL,
  \`tag_create\` tinyint(1) DEFAULT NULL,
  \`tag_edit\` tinyint(1) DEFAULT NULL,
  \`tag_archive\` tinyint(1) DEFAULT NULL,
  \`part_create\` tinyint(1) DEFAULT NULL,
  \`part_type_edit\` tinyint(1) DEFAULT NULL,
  \`part_edit\` tinyint(1) DEFAULT NULL,
  \`part_enabled\` tinyint(1) DEFAULT NULL,
  \`part_cost_edit\` tinyint(1) DEFAULT NULL,
  \`part_cost_view\` tinyint(1) DEFAULT NULL,
  \`part_archive\` tinyint(1) DEFAULT NULL,
  \`part_type_create\` tinyint(1) DEFAULT NULL,
  \`part_type_archive\` tinyint(1) DEFAULT NULL,
  \`procedure_template_create\` tinyint(1) DEFAULT NULL,
  \`procedure_template_edit\` tinyint(1) DEFAULT NULL,
  \`procedure_template_share_to_gpl\` tinyint(1) DEFAULT NULL,
  \`procedure_template_archive\` tinyint(1) DEFAULT NULL,
  \`vendor_create\` tinyint(1) DEFAULT NULL,
  \`vendor_edit\` tinyint(1) DEFAULT NULL,
  \`vendor_enabled\` tinyint(1) DEFAULT NULL,
  \`vendor_archive\` tinyint(1) DEFAULT NULL,
  \`email_work_order\` tinyint(1) DEFAULT NULL,
  \`invite_link_create\` tinyint(1) DEFAULT NULL,
  \`invite_link_edit\` tinyint(1) DEFAULT NULL,
  \`invite_link_list\` tinyint(1) DEFAULT NULL,
  \`invite_link_archive\` tinyint(1) DEFAULT NULL,
  \`entity_create_alias\` tinyint(1) DEFAULT NULL,
  \`entity_edit_alias\` tinyint(1) DEFAULT NULL,
  \`entity_archive_alias\` tinyint(1) DEFAULT NULL,
  \`asset_type_create\` tinyint(1) DEFAULT NULL,
  \`asset_type_archive\` tinyint(1) DEFAULT NULL,
  \`work_order_time_create\` tinyint(1) DEFAULT NULL,
  \`work_order_time_edit\` tinyint(1) DEFAULT NULL,
  \`work_order_time_archive\` tinyint(1) DEFAULT NULL,
  \`work_order_time_cost_view\` tinyint(1) DEFAULT NULL,
  \`work_order_time_rate_edit\` tinyint(1) DEFAULT NULL,
  \`work_order_expenditure_create\` tinyint(1) DEFAULT NULL,
  \`work_order_expenditure_edit\` tinyint(1) DEFAULT NULL,
  \`work_order_expenditure_archive\` tinyint(1) DEFAULT NULL,
  \`work_order_expenditure_cost_view\` tinyint(1) DEFAULT NULL,
  \`organization_invite\` tinyint(1) DEFAULT NULL,
  \`organization_remove\` tinyint(1) DEFAULT NULL,
  \`messaging\` tinyint(1) DEFAULT NULL,
  \`messaging_all_team_write\` tinyint(1) DEFAULT NULL,
  \`user_message_archive\` tinyint(1) DEFAULT NULL,
  \`user_list\` tinyint(1) DEFAULT NULL,
  \`procedure_file_picker_use\` tinyint(1) DEFAULT NULL,
  \`location_view\` tinyint(1) DEFAULT NULL,
  \`asset_view\` tinyint(1) DEFAULT NULL,
  \`billing_manage\` tinyint(1) DEFAULT NULL,
  \`meter_create\` tinyint(1) DEFAULT NULL,
  \`meter_edit\` tinyint(1) DEFAULT NULL,
  \`meter_archive\` tinyint(1) DEFAULT NULL,
  \`meter_reading_create\` tinyint(1) DEFAULT NULL,
  \`meter_reading_edit\` tinyint(1) DEFAULT NULL,
  \`meter_trigger_create\` tinyint(1) DEFAULT NULL,
  \`meter_trigger_edit\` tinyint(1) DEFAULT NULL,
  \`meter_trigger_archive\` tinyint(1) DEFAULT NULL,
  \`part_restock\` tinyint(1) DEFAULT NULL,
  \`purchase_order_approve\` tinyint(1) DEFAULT NULL,
  \`purchase_order_archive\` tinyint(1) DEFAULT NULL,
  \`purchase_order_edit\` tinyint(1) DEFAULT NULL,
  \`purchase_order_create\` tinyint(1) DEFAULT NULL,
  \`purchase_order_fulfill\` tinyint(1) DEFAULT NULL,
  \`purchase_order_view\` tinyint(1) DEFAULT NULL,
  \`vendor_contact_create\` tinyint(1) DEFAULT NULL,
  \`vendor_contact_edit\` tinyint(1) DEFAULT NULL,
  \`vendor_contact_archive\` tinyint(1) DEFAULT NULL,
  \`purchase_order_cancel\` tinyint(1) DEFAULT NULL,
  \`purchase_order_complete\` tinyint(1) DEFAULT NULL,
  \`purchase_order_cost_view\` tinyint(1) DEFAULT NULL,
  \`custom_field_create\` tinyint(1) DEFAULT NULL,
  \`custom_field_edit\` tinyint(1) DEFAULT NULL,
  \`custom_field_archive\` tinyint(1) DEFAULT NULL,
  \`custom_field_view\` tinyint(1) DEFAULT NULL,
  \`work_order_action_done_time_create\` tinyint(1) DEFAULT NULL,
  \`work_order_action_done_time_edit\` tinyint(1) DEFAULT NULL,
  \`work_order_action_done_expenditure_edit\` tinyint(1) DEFAULT NULL,
  \`custom_report_archive\` tinyint(1) DEFAULT NULL,
  \`custom_report_create\` tinyint(1) DEFAULT NULL,
  \`custom_report_edit\` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`permissions_organization_id_user_id_unique\` (\`organization_id\`,\`user_id\`),
  UNIQUE KEY \`permissions_organization_id_team_id_unique\` (\`organization_id\`,\`team_id\`),
  UNIQUE KEY \`permissions_organization_id_role_unique\` (\`organization_id\`,\`role\`),
  KEY \`permissions_user_id_foreign\` (\`user_id\`),
  CONSTRAINT \`permissions_organization_id_foreign\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`permissions_user_id_foreign\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
)`);

db.destroy();